version: '3.9'

services:
  redis-stack:
    container_name: redis-stack
    ports:
      - '6379:6379'
      - '8001:8001'
    image: 'redis/redis-stack:latest'
  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=dev
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - '3306:3306'
    volumes:
      - ./.things/db-data:/var/lib/mysql

volumes:
  db:
    driver: local
